const BOOKS = [
  {"id": 1, "title": "The Cornish Coast Murder", "author": "John Bude", "pubDate": "2014-03-31", "outOfPrint": false},
  {"id": 2, "title": "Lake District Murder", "author": "John Bude", "pubDate": "2014-03-31", "outOfPrint": false},
  {"id": 3, "title": "Murder Underground", "author": "Mavis Doriel Hay", "pubDate": "2014-04-04", "outOfPrint": false},
  {"id": 4, "title": "Death on the Cherwell", "author": "Mavis Doriel Hay", "pubDate": "2014-04-04", "outOfPrint": false},
  {"id": 5, "title": "A Scream in Soho", "author": "John G Brandon", "pubDate": "2014-10-15", "outOfPrint": false},
  {"id": 6, "title": "Mystery in White", "author": "J. Jefferson Farjeon", "pubDate": "2014-11-01", "outOfPrint": false},
  {"id": 7, "title": "Murder in Piccadilly", "author": "Charles Kingston", "pubDate": "2015-01-15", "outOfPrint": false},
  {"id": 8, "title": "Sussex Downs Murder", "author": "John Bude", "pubDate": "2015-01-15", "outOfPrint": false},
  {"id": 9, "title": "Capital Crimes", "author": "Martin Edwards (ed.)", "pubDate": "2015-03-12", "outOfPrint": false},
  {"id": 10, "title": "Antidote to Venom", "author": "Freeman Wills Crofts", "pubDate": "2015-04-02", "outOfPrint": false},
  {"id": 11, "title": "The Hog's Back Mystery", "author": "Freeman Wills Crofts", "pubDate": "2015-04-02", "outOfPrint": false},
  {"id": 12, "title": "Notting Hill Mystery", "author": "Charles Warren Adams", "pubDate": "2015-05-01", "outOfPrint": false},
  {"id": 13, "title": "Resorting to Murder", "author": "Martin Edwards (ed.)", "pubDate": "2015-05-07", "outOfPrint": false},
  {"id": 14, "title": "Quick Curtain", "author": "Alan Melville", "pubDate": "2015-07-02", "outOfPrint": false},
  {"id": 15, "title": "Death of an Airman", "author": "Christopher St John Sprigg", "pubDate": "2015-08-04", "outOfPrint": false},
  {"id": 16, "title": "Death of Anton", "author": "Alan Melville", "pubDate": "2015-08-04", "outOfPrint": false},
  {"id": 17, "title": "Thirteen Guests", "author": "J. Jefferson Farjeon", "pubDate": "2015-09-03", "outOfPrint": false},
  {"id": 18, "title": "Z Murders", "author": "J. Jefferson Farjeon", "pubDate": "2015-09-03", "outOfPrint": false},
  {"id": 19, "title": "Silent Nights", "author": "Martin Edwards (ed.)", "pubDate": "2015-10-01", "outOfPrint": false},
  {"id": 20, "title": "The Santa Klaus Murder", "author": "Mavis Doriel Hay", "pubDate": "2015-10-01", "outOfPrint": false},
  {"id": 21, "title": "Murder of a Lady", "author": "Anthony Wynne", "pubDate": "2016-01-01", "outOfPrint": false},
  {"id": 22, "title": "Death on the Riviera", "author": "John Bude", "pubDate": "2016-01-01", "outOfPrint": false},
  {"id": 23, "title": "Murder at the Manor", "author": "Martin Edwards (ed.)", "pubDate": "2016-02-01", "outOfPrint": false},
  {"id": 24, "title": "Serpents in Eden", "author": "Martin Edwards (ed.)", "pubDate": "2016-03-01", "outOfPrint": false},
  {"id": 25, "title": "Calamity in Kent", "author": "John Rowland", "pubDate": "2016-04-01", "outOfPrint": false},
  {"id": 26, "title": "Death in the Tunnel", "author": "Miles Burton", "pubDate": "2016-05-01", "outOfPrint": false},
  {"id": 27, "title": "Murder in the Museum", "author": "John Rowland", "pubDate": "2016-05-03", "outOfPrint": true},
  {"id": 28, "title": "Secret of High Eldersham", "author": "Miles Burton", "pubDate": "2016-06-01", "outOfPrint": false},
  {"id": 29, "title": "Sergeant Cluff Stands Firm", "author": "Gil North", "pubDate": "2016-07-10", "outOfPrint": false},
  {"id": 30, "title": "12.30 from Croydon", "author": "Freeman Wills Crofts", "pubDate": "2016-07-10", "outOfPrint": false},
  {"id": 31, "title": "The Cheltenham Square Murder", "author": "John Bude", "pubDate": "2016-08-10", "outOfPrint": false},
  {"id": 32, "title": "Methods of Sergeant Cluff", "author": "Gil North", "pubDate": "2016-09-10", "outOfPrint": false},
  {"id": 33, "title": "Mystery in the Channel", "author": "Freeman Wills Crofts", "pubDate": "2016-09-10", "outOfPrint": false},
  {"id": 34, "title": "Death of a Busybody", "author": "George Bellairs", "pubDate": "2016-10-06", "outOfPrint": false},
  {"id": 35, "title": "The Poisoned Chocolates Case", "author": "Anthony Berkeley", "pubDate": "2016-10-10", "outOfPrint": false},
  {"id": 36, "title": "Crimson Snow", "author": "Martin Edwards (ed.)", "pubDate": "2016-11-10", "outOfPrint": false},
  {"id": 37, "title": "The Dead Shall Be Raised & Murder of a Quack", "author": "George Bellairs", "pubDate": "2016-12-10", "outOfPrint": false},
  {"id": 38, "title": "Death Makes a Prophet", "author": "John Bude", "pubDate": "2017-01-01", "outOfPrint": false},
  {"id": 39, "title": "Verdict of Twelve", "author": "Raymond Postgate", "pubDate": "2017-01-10", "outOfPrint": false},
  {"id": 40, "title": "Scarweather", "author": "Anthony Rolls", "pubDate": "2017-02-10", "outOfPrint": false},
  {"id": 41, "title": "Family Matters", "author": "Anthony Rolls", "pubDate": "2017-03-10", "outOfPrint": false},
  {"id": 42, "title": "Miraculous Mysteries", "author": "Martin Edwards (ed.)", "pubDate": "2017-04-10", "outOfPrint": false},
  {"id": 43, "title": "The Incredible Crime", "author": "Lois Austen-Leigh", "pubDate": "2017-05-10", "outOfPrint": false},
  {"id": 44, "title": "Continental Crimes", "author": "Martin Edwards (ed.)", "pubDate": "2017-06-10", "outOfPrint": false},
  {"id": 45, "title": "The Long Arm of the Law: Classic Police Stories", "author": "Martin Edwards (ed.)", "pubDate": "2017-07-10", "outOfPrint": false},
  {"id": 46, "title": "Seven Dead", "author": "J. Jefferson Farjeon", "pubDate": "2017-09-04", "outOfPrint": false},
  {"id": 47, "title": "Portrait of a Murderer", "author": "Anne Meredith", "pubDate": "2017-09-10", "outOfPrint": false},
  {"id": 48, "title": "Somebody at the Door", "author": "Raymond Postgate", "pubDate": "2017-09-28", "outOfPrint": false},
  {"id": 49, "title": "Foreign Bodies", "author": "Martin Edwards (ed.)", "pubDate": "2017-10-05", "outOfPrint": false},
  {"id": 50, "title": "Bats in the Belfry", "author": "E. C. R. Lorac", "pubDate": "2018-01-10", "outOfPrint": false},
  {"id": 51, "title": "Fire in the Thatch", "author": "E. C. R. Lorac", "pubDate": "2018-02-10", "outOfPrint": false},
  {"id": 52, "title": "Blood on the Tracks", "author": "Martin Edwards (ed.)", "pubDate": "2018-02-28", "outOfPrint": false},
  {"id": 53, "title": "Murder of My Aunt", "author": "Richard Hull", "pubDate": "2018-04-04", "outOfPrint": false},
  {"id": 54, "title": "Excellent Intentions", "author": "Richard Hull", "pubDate": "2018-05-01", "outOfPrint": false},
  {"id": 55, "title": "Weekend at Thrackley", "author": "Alan Melville", "pubDate": "2018-05-25", "outOfPrint": false},
  {"id": 56, "title": "The Arsenal Stadium Mystery", "author": "Leonard Gribble", "pubDate": "2018-07-10", "outOfPrint": false},
  {"id": 57, "title": "The Division Bell Mystery", "author": "Ellen Wilkinson", "pubDate": "2018-08-10", "outOfPrint": false},
  {"id": 58, "title": "The Belting Inheritance", "author": "Julian Symons", "pubDate": "2018-09-10", "outOfPrint": false},
  {"id": 59, "title": "The Christmas Card Crime", "author": "Martin Edwards (ed.)", "pubDate": "2018-10-10", "outOfPrint": false},
  {"id": 60, "title": "Murder by Matchlight", "author": "E. C. R. Lorac", "pubDate": "2018-11-10", "outOfPrint": false},
  {"id": 61, "title": "Smallbone Deceased", "author": "Michael Gilbert", "pubDate": "2019-01-10", "outOfPrint": false},
  {"id": 62, "title": "The Colour of Murder", "author": "Julian Symons", "pubDate": "2019-02-01", "outOfPrint": false},
  {"id": 63, "title": "Death in Captivity", "author": "Michael Gilbert", "pubDate": "2019-02-10", "outOfPrint": false},
  {"id": 64, "title": "Death Has Deep Roots", "author": "Michael Gilbert", "pubDate": "2019-03-10", "outOfPrint": false},
  {"id": 65, "title": "Surfeit of Suspects", "author": "George Bellairs", "pubDate": "2019-04-10", "outOfPrint": false},
  {"id": 66, "title": "Murder in the Mill-Race", "author": "E. C. R. Lorac", "pubDate": "2019-05-10", "outOfPrint": false},
  {"id": 67, "title": "Deep Waters", "author": "Martin Edwards (ed.)", "pubDate": "2019-06-10", "outOfPrint": false},
  {"id": 68, "title": "Fell Murder", "author": "E. C. R. Lorac", "pubDate": "2019-07-10", "outOfPrint": false},
  {"id": 69, "title": "The Body in the Dumb River", "author": "George Bellairs", "pubDate": "2019-08-10", "outOfPrint": false},
  {"id": 70, "title": "It Walks by Night", "author": "John Dickson Carr", "pubDate": "2019-09-10", "outOfPrint": false},
  {"id": 71, "title": "The Measure of Malice", "author": "Martin Edwards (ed.)", "pubDate": "2019-09-10", "outOfPrint": false},
  {"id": 72, "title": "The Christmas Egg", "author": "Mary Kelly", "pubDate": "2019-10-10", "outOfPrint": false},
  {"id": 73, "title": "Death in Fancy Dress", "author": "Anthony Gilbert", "pubDate": "2019-11-10", "outOfPrint": false},
  {"id": 74, "title": "Castle Skull", "author": "John Dickson Carr", "pubDate": "2020-01-10", "outOfPrint": false},
  {"id": 75, "title": "Death in White Pyjamas", "author": "John Bude", "pubDate": "2020-02-10", "outOfPrint": false},
  {"id": 76, "title": "Settling Scores", "author": "Martin Edwards (ed.)", "pubDate": "2020-03-10", "outOfPrint": false},
  {"id": 77, "title": "Crossed Skis", "author": "Carol Carnac", "pubDate": "2020-04-10", "outOfPrint": false},
  {"id": 78, "title": "The Spoilt Kill", "author": "Mary Kelly", "pubDate": "2020-05-10", "outOfPrint": false},
  {"id": 79, "title": "Woman In The Wardrobe", "author": "Peter Shaffer", "pubDate": "2020-06-10", "outOfPrint": false},
  {"id": 80, "title": "The Man Who Didn't Fly", "author": "Margot Bennett", "pubDate": "2020-07-10", "outOfPrint": false},
  {"id": 81, "title": "Checkmate to Murder", "author": "E. C. R. Lorac", "pubDate": "2020-08-10", "outOfPrint": false},
  {"id": 82, "title": "The Progress of a Crime", "author": "Julian Symons", "pubDate": "2020-09-10", "outOfPrint": false},
  {"id": 83, "title": "A Surprise for Christmas", "author": "Martin Edwards (ed.)", "pubDate": "2020-10-10", "outOfPrint": false},
  {"id": 84, "title": "The Port of London Murders", "author": "Josephine Bell", "pubDate": "2020-10-10", "outOfPrint": false},
  {"id": 85, "title": "The Lost Gallows", "author": "John Dickson Carr", "pubDate": "2020-11-10", "outOfPrint": false},
  {"id": 86, "title": "The Corpse in the Waxworks", "author": "John Dickson Carr", "pubDate": "2021-01-10", "outOfPrint": false},
  {"id": 87, "title": "Murder's a Swine", "author": "Nap Lombard", "pubDate": "2021-02-10", "outOfPrint": false},
  {"id": 88, "title": "Two-Way Murder", "author": "E. C. R. Lorac", "pubDate": "2021-03-10", "outOfPrint": false},
  {"id": 89, "title": "Due to a Death", "author": "Mary Kelly", "pubDate": "2021-04-10", "outOfPrint": false},
  {"id": 90, "title": "The Chianti Flask", "author": "Marie Belloc Lowndes", "pubDate": "2021-05-10", "outOfPrint": false},
  {"id": 91, "title": "Guilty Creatures", "author": "Martin Edwards (ed.)", "pubDate": "2021-06-10", "outOfPrint": false},
  {"id": 92, "title": "The Widow of Bath", "author": "Margot Bennett", "pubDate": "2021-07-10", "outOfPrint": false},
  {"id": 93, "title": "Murder by the Book", "author": "Martin Edwards (ed.)", "pubDate": "2021-08-10", "outOfPrint": false},
  {"id": 94, "title": "Till Death Do Us Part", "author": "John Dickson Carr", "pubDate": "2021-09-10", "outOfPrint": false},
  {"id": 95, "title": "These Names Make Clues", "author": "E. C. R. Lorac", "pubDate": "2021-09-10", "outOfPrint": false},
  {"id": 96, "title": "Murder After Christmas", "author": "Rupert Latimer", "pubDate": "2021-10-10", "outOfPrint": false},
  {"id": 97, "title": "Murder in the Basement", "author": "Anthony Berkeley", "pubDate": "2021-11-10", "outOfPrint": false},
  {"id": 98, "title": "Jumping Jenny", "author": "Anthony Berkeley", "pubDate": "2022-01-10", "outOfPrint": false},
  {"id": 99, "title": "Post After Post-Mortem", "author": "E. C. R. Lorac", "pubDate": "2022-02-10", "outOfPrint": false},
  {"id": 100, "title": "Death of a Bookseller", "author": "Bernard J. Farmer", "pubDate": "2022-03-17", "outOfPrint": false},
  {"id": 101, "title": "Green for Danger", "author": "Christianna Brand", "pubDate": "2022-04-10", "outOfPrint": false},
  {"id": 102, "title": "The Edinburgh Mystery", "author": "Martin Edwards (ed.)", "pubDate": "2022-05-10", "outOfPrint": false},
  {"id": 103, "title": "The Seat of the Scornful", "author": "John Dickson Carr", "pubDate": "2022-06-10", "outOfPrint": false},
  {"id": 104, "title": "Crook o'Lune", "author": "E. C. R. Lorac", "pubDate": "2022-07-10", "outOfPrint": false},
  {"id": 105, "title": "Death of Jezebel", "author": "Christianna Brand", "pubDate": "2022-08-10", "outOfPrint": false},
  {"id": 106, "title": "Death on the Down Beat", "author": "Sebastian Farr", "pubDate": "2022-09-10", "outOfPrint": false},
  {"id": 107, "title": "Final Acts", "author": "Martin Edwards (ed.)", "pubDate": "2022-09-10", "outOfPrint": false},
  {"id": 108, "title": "The White Priory Murders", "author": "John Dickson Carr", "pubDate": "2022-10-10", "outOfPrint": false},
  {"id": 109, "title": "The Mysterious Mr. Badman", "author": "W. F. Harvey", "pubDate": "2022-11-10", "outOfPrint": false},
  {"id": 110, "title": "Death of an Author", "author": "E. C. R. Lorac", "pubDate": "2023-01-10", "outOfPrint": false},
  {"id": 111, "title": "Death of Mr Dodsley", "author": "John Ferguson", "pubDate": "2023-02-10", "outOfPrint": false},
  {"id": 112, "title": "The Black Spectacles", "author": "John Dickson Carr", "pubDate": "2023-03-10", "outOfPrint": false},
  {"id": 113, "title": "Twice Round the Clock", "author": "Billie Houston", "pubDate": "2023-04-10", "outOfPrint": false},
  {"id": 114, "title": "Crimes of Cymru: Classic Mystery Tales of Wales", "author": "Martin Edwards (ed.)", "pubDate": "2023-05-10", "outOfPrint": false},
  {"id": 115, "title": "Suddenly at His Residence", "author": "Christianna Brand", "pubDate": "2023-06-10", "outOfPrint": false},
  {"id": 116, "title": "The Wheel Spins", "author": "Ethel Lina White", "pubDate": "2023-07-10", "outOfPrint": false},
  {"id": 117, "title": "He Who Whispers", "author": "John Dickson Carr", "pubDate": "2023-08-10", "outOfPrint": false},
  {"id": 118, "title": "The Theft of the Iron Dogs", "author": "E. C. R. Lorac", "pubDate": "2023-09-10", "outOfPrint": false},
  {"id": 119, "title": "Who Killed Father Christmas?", "author": "Martin Edwards (ed.)", "pubDate": "2023-10-10", "outOfPrint": false},
  {"id": 120, "title": "Big Ben Strikes Eleven", "author": "David Magarshack", "pubDate": "2023-11-10", "outOfPrint": false},
  {"id": 121, "title": "Someone from the Past", "author": "Margot Bennett", "pubDate": "2023-12-10", "outOfPrint": false},
  {"id": 122, "title": "Fear Stalks the Village", "author": "Ethel Lina White", "pubDate": "2024-01-10", "outOfPrint": false},
  {"id": 123, "title": "Impact of Evidence", "author": "Carol Carnac", "pubDate": "2024-02-10", "outOfPrint": false},
  {"id": 124, "title": "A Telegram from Le Touquet", "author": "John Bude", "pubDate": "2024-03-10", "outOfPrint": false},
  {"id": 125, "title": "London Particular", "author": "Christianna Brand", "pubDate": "2024-04-10", "outOfPrint": false},
  {"id": 126, "title": "Before the Fact", "author": "Frances Iles", "pubDate": "2024-05-10", "outOfPrint": false},
  {"id": 127, "title": "Lessons in Crime", "author": "Martin Edwards (ed.)", "pubDate": "2024-06-10", "outOfPrint": false},
  {"id": 128, "title": "Tour de Force", "author": "Christianna Brand", "pubDate": "2024-07-10", "outOfPrint": false},
  {"id": 129, "title": "Mr. Pottermack's Oversight", "author": "R. Austin Freeman", "pubDate": "2024-08-10", "outOfPrint": false},
  {"id": 130, "title": "Metropolitan Mysteries", "author": "Martin Edwards (ed.)", "pubDate": "2024-09-10", "outOfPrint": false},
  {"id": 131, "title": "Dramatic Murder", "author": "Elizabeth Anthony", "pubDate": "2024-10-10", "outOfPrint": false},
  {"id": 132, "title": "Murder in Vienna", "author": "E. C. R. Lorac", "pubDate": "2024-11-10", "outOfPrint": false},
  {"id": 133, "title": "Tea on Sunday", "author": "Lettice Cooper", "pubDate": "2024-12-10", "outOfPrint": false},
  {"id": 134, "title": "Murder as a Fine Art", "author": "Carol Carnac", "pubDate": "2025-01-10", "outOfPrint": false},
  {"id": 135, "title": "The Ten Teacups", "author": "Carter Dickson", "pubDate": "2025-02-10", "outOfPrint": false},
  {"id": 136, "title": "Not to Be Taken", "author": "Anthony Berkeley", "pubDate": "2025-03-25", "outOfPrint": false},
  {"id": 137, "title": "Scandalize My Name", "author": "Fiona Sinclair", "pubDate": "2025-04-10", "outOfPrint": false},
  {"id": 138, "title": "Cat and Mouse", "author": "Christianna Brand", "pubDate": "2025-05-10", "outOfPrint": false},
  {"id": 139, "title": "Cyanide in the Sun: And Other Stories of Summertime Crime", "author": "Martin Edwards (ed.)", "pubDate": "2025-06-10", "outOfPrint": false},
  {"id": 140, "title": "The Judas Window", "author": "Carter Dickson", "pubDate": "2025-07-10", "outOfPrint": false},
  {"id": 141, "title": "The Odd Flamingo", "author": "Nina Bawden", "pubDate": "2025-08-10", "outOfPrint": false},
  {"id": 142, "title": "As If By Magic", "author": "Martin Edwards (ed.)", "pubDate": "2025-09-10", "outOfPrint": false},
  {"id": 143, "title": "Death in Ambush", "author": "Susan Gilruth", "pubDate": "2025-10-10", "outOfPrint": false},
  {"id": 144, "title": "Death in High Heels", "author": "Christianna Brand", "pubDate": "2025-11-10", "outOfPrint": false},
  {"id": 145, "title": "Still Waters: A Lake District Mystery", "author": "E. C. R. Lorac", "pubDate": "2025-12-10", "outOfPrint": false},
  {"id": 146, "title": "Sky High", "author": "Michael Gilbert", "pubDate": "2026-01-10", "outOfPrint": false},
  {"id": 147, "title": "The Double Turn", "author": "Carol Carnac", "pubDate": "2026-02-10", "outOfPrint": false},
  {"id": 148, "title": "Airing in a Closed Carriage", "author": "Mark Morris (ed.)", "pubDate": "2026-03-19", "outOfPrint": false},
  {"id": 149, "title": "Jack on the Gallows Tree", "author": "Leo Bruce", "pubDate": "2026-04-10", "outOfPrint": false},
  {"id": 150, "title": "The Unicorn Murders", "author": "Carter Dickson", "pubDate": "2026-05-07", "outOfPrint": false},
  {"id": 151, "title": "Puzzles of the Parish: Short Tales of Ministers, Murder and Mystery", "author": "Martin Edwards (ed.)", "pubDate": "2026-06-10", "outOfPrint": false}
]
;